server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: 1c_logs
  relabel_configs:
    - source_labels: [__filename__]
      regex: /logs/(.*).json
      target_label: project
  static_configs:
  - targets:
      - localhost
    labels:
      job: 1c_logs
      __path__: /logs/*.json


- job_name: converter_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: converter_logs
      __path__: /app-logs/*.log
